# Generated by Django 2.2.10 on 2020-07-26 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0004_auto_20200726_0739'),
        ('accounts', '0002_auto_20200726_0739'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='User',
        ),
    ]
