# Generated by Django 2.2.10 on 2020-12-24 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201223_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ref_code',
            field=models.CharField(default='timezone.now', max_length=20),
            preserve_default=False,
        ),
    ]
