# Generated by Django 2.2.10 on 2020-12-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='ref_code',
            field=models.CharField(default='timezone.now', max_length=20),
            preserve_default=False,
        ),
    ]
